apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-namespace

commonLabels:
  app: tiller

images:
- name: gcr.io/kubernetes-helm/tiller:v2.14.0
- newTag: v2.14.0

resources:
- deployment.yaml
- service.yaml
- service-account.yaml
- service-account-role.yaml
- service-account-role-binding.yaml